<?php 
/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

namespace FouleFactoryApiLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CsvFileWriterServiceModel implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @maps IdProject
     * @var integer $idProject public property
     */
    public $idProject;

    /**
     * @todo Write general description for this property
     * @required
     * @maps File
     * @var string $file public property
     */
    public $file;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Header
     * @var bool $header public property
     */
    public $header;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Separator
     * @var string $separator public property
     */
    public $separator;

    /**
     * Constructor to set initial or default values of member properties
     * @param   integer           $idProject   Initialization value for the property $this->idProject
     * @param   string            $file        Initialization value for the property $this->file     
     * @param   bool              $header      Initialization value for the property $this->header   
     * @param   string            $separator   Initialization value for the property $this->separator
     */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->idProject = func_get_arg(0);
            $this->file      = func_get_arg(1);
            $this->header    = func_get_arg(2);
            $this->separator = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['IdProject'] = $this->idProject;
        $json['File']      = $this->file;
        $json['Header']    = $this->header;
        $json['Separator'] = $this->separator;

        return $json;
    }
}