<?php 
/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

namespace FouleFactoryApiLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ProjectWriterServiceModel implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @maps IdTemplate
     * @var integer $idTemplate public property
     */
    public $idTemplate;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Title
     * @var string $title public property
     */
    public $title;

    /**
     * @todo Write general description for this property
     * @required
     * @maps EstimatedTimePerTask
     * @var string $estimatedTimePerTask public property
     */
    public $estimatedTimePerTask;

    /**
     * @todo Write general description for this property
     * @required
     * @maps NbSupplierPerTask
     * @var integer $nbSupplierPerTask public property
     */
    public $nbSupplierPerTask;

    /**
     * @todo Write general description for this property
     * @required
     * @maps AmountWithoutTaxPerTask
     * @var integer $amountWithoutTaxPerTask public property
     */
    public $amountWithoutTaxPerTask;

    /**
     * @todo Write general description for this property
     * @required
     * @maps AutomaticValidation
     * @var bool $automaticValidation public property
     */
    public $automaticValidation;

    /**
     * @todo Write general description for this property
     * @maps MaxEndDate
     * @var string $maxEndDate public property
     */
    public $maxEndDate;

    /**
     * @todo Write general description for this property
     * @maps IdCertification
     * @var integer $idCertification public property
     */
    public $idCertification;

    /**
     * @todo Write general description for this property
     * @maps UrlNotification
     * @var string $urlNotification public property
     */
    public $urlNotification;

    /**
     * Constructor to set initial or default values of member properties
     * @param   integer           $idTemplate                Initialization value for the property $this->idTemplate             
     * @param   string            $title                     Initialization value for the property $this->title                  
     * @param   string            $estimatedTimePerTask      Initialization value for the property $this->estimatedTimePerTask   
     * @param   integer           $nbSupplierPerTask         Initialization value for the property $this->nbSupplierPerTask      
     * @param   integer           $amountWithoutTaxPerTask   Initialization value for the property $this->amountWithoutTaxPerTask
     * @param   bool              $automaticValidation       Initialization value for the property $this->automaticValidation    
     * @param   string            $maxEndDate                Initialization value for the property $this->maxEndDate             
     * @param   integer           $idCertification           Initialization value for the property $this->idCertification        
     * @param   string            $urlNotification           Initialization value for the property $this->urlNotification        
     */
    public function __construct()
    {
        if(9 == func_num_args())
        {
            $this->idTemplate              = func_get_arg(0);
            $this->title                   = func_get_arg(1);
            $this->estimatedTimePerTask    = func_get_arg(2);
            $this->nbSupplierPerTask       = func_get_arg(3);
            $this->amountWithoutTaxPerTask = func_get_arg(4);
            $this->automaticValidation     = func_get_arg(5);
            $this->maxEndDate              = func_get_arg(6);
            $this->idCertification         = func_get_arg(7);
            $this->urlNotification         = func_get_arg(8);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['IdTemplate']              = $this->idTemplate;
        $json['Title']                   = $this->title;
        $json['EstimatedTimePerTask']    = $this->estimatedTimePerTask;
        $json['NbSupplierPerTask']       = $this->nbSupplierPerTask;
        $json['AmountWithoutTaxPerTask'] = $this->amountWithoutTaxPerTask;
        $json['AutomaticValidation']     = $this->automaticValidation;
        $json['MaxEndDate']              = $this->maxEndDate;
        $json['IdCertification']         = $this->idCertification;
        $json['UrlNotification']         = $this->urlNotification;

        return $json;
    }
}