<?php 
/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

namespace FouleFactoryApiLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TaskLinesWriterServiceModel implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @maps IdProject
     * @var integer $idProject public property
     */
    public $idProject;

    /**
     * @todo Write general description for this property
     * @required
     * @maps TaskColumns
     * @var array $taskColumns public property
     */
    public $taskColumns;

    /**
     * Constructor to set initial or default values of member properties
     * @param   integer           $idProject     Initialization value for the property $this->idProject  
     * @param   array             $taskColumns   Initialization value for the property $this->taskColumns
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->idProject   = func_get_arg(0);
            $this->taskColumns = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['IdProject']   = $this->idProject;
        $json['TaskColumns'] = $this->taskColumns;

        return $json;
    }
}