<?php 
/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

namespace FouleFactoryApiLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TaskValidationWriterServiceModel implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @maps IdTask
     * @var integer $idTask public property
     */
    public $idTask;

    /**
     * @todo Write general description for this property
     * @maps State
     * @var string $state public property
     */
    public $state;

    /**
     * Constructor to set initial or default values of member properties
     * @param   integer           $idTask   Initialization value for the property $this->idTask
     * @param   string            $state    Initialization value for the property $this->state 
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->idTask = func_get_arg(0);
            $this->state  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['IdTask'] = $this->idTask;
        $json['State']  = $this->state;

        return $json;
    }
}