<?php 
/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

namespace FouleFactoryApiLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TemplateNewWriterServiceModel implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @maps IdProjectType
     * @var integer $idProjectType public property
     */
    public $idProjectType;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Title
     * @var string $title public property
     */
    public $title;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Description
     * @var string $description public property
     */
    public $description;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Instructions
     * @var TemplateInstructionWriterServiceModel[] $instructions public property
     */
    public $instructions;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Columns
     * @var TemplateColumnWriterServiceModel[] $columns public property
     */
    public $columns;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Questions
     * @var TemplateQuestionWriterServiceModel[] $questions public property
     */
    public $questions;

    /**
     * Constructor to set initial or default values of member properties
     * @param   integer           $idProjectType   Initialization value for the property $this->idProjectType
     * @param   string            $title           Initialization value for the property $this->title        
     * @param   string            $description     Initialization value for the property $this->description  
     * @param   array             $instructions    Initialization value for the property $this->instructions 
     * @param   array             $columns         Initialization value for the property $this->columns      
     * @param   array             $questions       Initialization value for the property $this->questions    
     */
    public function __construct()
    {
        if(6 == func_num_args())
        {
            $this->idProjectType = func_get_arg(0);
            $this->title         = func_get_arg(1);
            $this->description   = func_get_arg(2);
            $this->instructions  = func_get_arg(3);
            $this->columns       = func_get_arg(4);
            $this->questions     = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['IdProjectType'] = $this->idProjectType;
        $json['Title']         = $this->title;
        $json['Description']   = $this->description;
        $json['Instructions']  = $this->instructions;
        $json['Columns']       = $this->columns;
        $json['Questions']     = $this->questions;

        return $json;
    }
}