<?php 
/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

namespace FouleFactoryApiLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class TemplateInstructionWriterServiceModel implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @maps Instruction
     * @var string $instruction public property
     */
    public $instruction;

    /**
     * @todo Write general description for this property
     * @required
     * @maps Order
     * @var integer $order public property
     */
    public $order;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $instruction   Initialization value for the property $this->instruction
     * @param   integer           $order         Initialization value for the property $this->order      
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->instruction = func_get_arg(0);
            $this->order       = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Instruction'] = $this->instruction;
        $json['Order']       = $this->order;

        return $json;
    }
}