<?php
/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */

namespace FouleFactoryApiLib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class. 
 */
class Configuration {
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'http://api.foulefactory.com';

    /**
     * The username to use with basic authentication
     * @var string
     */
    /**
     * @todo Replace the $basicAuthUserName with an appropriate value
     */
    public static $basicAuthUserName = 'TODO: Replace';

    /**
     * The password to use with basic authentication
     * @var string
     */
    /**
     * @todo Replace the $basicAuthPassword with an appropriate value
     */
    public static $basicAuthPassword = 'TODO: Replace';

}
